# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "[joÀê&#39;hana]" # Your name
  description: "" # A brief slogan (optional)
  # image: <a href="https://www.samcronenberg.com/">img/paris_bySam.jpg</a>
  
  favicon: img/icon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
#    logo: /img/icon.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      # - text: "CV"
      #   href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:johanna.cronenberg@u-paris.fr"
      - text: "{{< iconify academicons researchgate >}}"
        href: https://www.researchgate.net/profile/Johanna_Cronenberg
      - text: "{{< iconify academicons google-scholar >}}"
        href: https://scholar.google.com/citations?hl=en&user=SPj8914AAAAJ
      - icon: github
        href: https://github.com/johannacronenberg
      


# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
#     center: |
#       <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
#     right: |
#       <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true